// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category_attributes.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCategoryAttribute = `-- name: CreateCategoryAttribute :one
INSERT INTO category_attributes (
    id,
    category_id,
    name,
    data_type,
    is_required
) VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4
)
RETURNING id, category_id, name, data_type, is_required, created_at
`

type CreateCategoryAttributeParams struct {
	CategoryID uuid.UUID    `json:"category_id"`
	Name       string       `json:"name"`
	DataType   string       `json:"data_type"`
	IsRequired sql.NullBool `json:"is_required"`
}

func (q *Queries) CreateCategoryAttribute(ctx context.Context, arg CreateCategoryAttributeParams) (CategoryAttribute, error) {
	row := q.db.QueryRow(ctx, createCategoryAttribute,
		arg.CategoryID,
		arg.Name,
		arg.DataType,
		arg.IsRequired,
	)
	var i CategoryAttribute
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.DataType,
		&i.IsRequired,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategoryAttribute = `-- name: DeleteCategoryAttribute :exec
DELETE FROM category_attributes
WHERE id = $1
`

func (q *Queries) DeleteCategoryAttribute(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategoryAttribute, id)
	return err
}

const getCategoryAttribute = `-- name: GetCategoryAttribute :one
SELECT id, category_id, name, data_type, is_required, created_at
FROM category_attributes
WHERE category_id = $1
  AND name = $2
`

type GetCategoryAttributeParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	Name       string    `json:"name"`
}

func (q *Queries) GetCategoryAttribute(ctx context.Context, arg GetCategoryAttributeParams) (CategoryAttribute, error) {
	row := q.db.QueryRow(ctx, getCategoryAttribute, arg.CategoryID, arg.Name)
	var i CategoryAttribute
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.DataType,
		&i.IsRequired,
		&i.CreatedAt,
	)
	return i, err
}

const listCategoryAttributes = `-- name: ListCategoryAttributes :many
SELECT id, category_id, name, data_type, is_required, created_at
FROM category_attributes
WHERE category_id = $1
ORDER BY name
`

func (q *Queries) ListCategoryAttributes(ctx context.Context, categoryID uuid.UUID) ([]CategoryAttribute, error) {
	rows, err := q.db.Query(ctx, listCategoryAttributes, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryAttribute{}
	for rows.Next() {
		var i CategoryAttribute
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.DataType,
			&i.IsRequired,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
