// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: itemcatagory.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createItemCategory = `-- name: CreateItemCategory :one
INSERT INTO item_category (
    name,
    description
) VALUES (
    $1, $2
) RETURNING id, name, description
`

type CreateItemCategoryParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateItemCategory(ctx context.Context, arg CreateItemCategoryParams) (ItemCategory, error) {
	row := q.db.QueryRow(ctx, createItemCategory, arg.Name, arg.Description)
	var i ItemCategory
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const deleteItemCategory = `-- name: DeleteItemCategory :exec
DELETE FROM item_category
WHERE id = $1
`

func (q *Queries) DeleteItemCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteItemCategory, id)
	return err
}

const getItemCategoryByID = `-- name: GetItemCategoryByID :one
SELECT id, name, description
FROM item_category
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetItemCategoryByID(ctx context.Context, id uuid.UUID) (ItemCategory, error) {
	row := q.db.QueryRow(ctx, getItemCategoryByID, id)
	var i ItemCategory
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const listItemCategories = `-- name: ListItemCategories :many
SELECT id, name, description
FROM item_category
ORDER BY name ASC
`

func (q *Queries) ListItemCategories(ctx context.Context) ([]ItemCategory, error) {
	rows, err := q.db.Query(ctx, listItemCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemCategory{}
	for rows.Next() {
		var i ItemCategory
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemCategory = `-- name: UpdateItemCategory :one
UPDATE item_category
SET
    name = COALESCE($2, name),
    description = COALESCE($3, description)
WHERE id = $1
RETURNING id, name, description
`

type UpdateItemCategoryParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateItemCategory(ctx context.Context, arg UpdateItemCategoryParams) (ItemCategory, error) {
	row := q.db.QueryRow(ctx, updateItemCategory, arg.ID, arg.Name, arg.Description)
	var i ItemCategory
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}
