// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction_item_attributes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteTransactionItemAttributes = `-- name: DeleteTransactionItemAttributes :exec
DELETE FROM transaction_item_attributes
WHERE transaction_id = $1
`

func (q *Queries) DeleteTransactionItemAttributes(ctx context.Context, transactionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransactionItemAttributes, transactionID)
	return err
}

const getEscrowItemAttribute = `-- name: GetEscrowItemAttribute :one
SELECT id, transaction_id, attribute_id, value, created_at
FROM transaction_item_attributes
WHERE transaction_id = $1
  AND attribute_id = $2
`

type GetEscrowItemAttributeParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	AttributeID   uuid.UUID `json:"attribute_id"`
}

func (q *Queries) GetEscrowItemAttribute(ctx context.Context, arg GetEscrowItemAttributeParams) (TransactionItemAttribute, error) {
	row := q.db.QueryRow(ctx, getEscrowItemAttribute, arg.TransactionID, arg.AttributeID)
	var i TransactionItemAttribute
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.AttributeID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const insertTransactionItemAttribute = `-- name: InsertTransactionItemAttribute :one
INSERT INTO transaction_item_attributes (
    id,
    transaction_id,
    attribute_id,
    value
) VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3
)
RETURNING id, transaction_id, attribute_id, value, created_at
`

type InsertTransactionItemAttributeParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	AttributeID   uuid.UUID `json:"attribute_id"`
	Value         string    `json:"value"`
}

func (q *Queries) InsertTransactionItemAttribute(ctx context.Context, arg InsertTransactionItemAttributeParams) (TransactionItemAttribute, error) {
	row := q.db.QueryRow(ctx, insertTransactionItemAttribute, arg.TransactionID, arg.AttributeID, arg.Value)
	var i TransactionItemAttribute
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.AttributeID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactionItemAttributes = `-- name: ListTransactionItemAttributes :many
SELECT
    eia.id,
    eia.transaction_id,
    ca.name AS attribute_name,
    ca.data_type,
    eia.value
FROM transaction_item_attributes eia
JOIN category_attributes ca
  ON ca.id = eia.attribute_id
WHERE eia.transaction_id = $1
`

type ListTransactionItemAttributesRow struct {
	ID            uuid.UUID `json:"id"`
	TransactionID uuid.UUID `json:"transaction_id"`
	AttributeName string    `json:"attribute_name"`
	DataType      string    `json:"data_type"`
	Value         string    `json:"value"`
}

func (q *Queries) ListTransactionItemAttributes(ctx context.Context, transactionID uuid.UUID) ([]ListTransactionItemAttributesRow, error) {
	rows, err := q.db.Query(ctx, listTransactionItemAttributes, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionItemAttributesRow{}
	for rows.Next() {
		var i ListTransactionItemAttributesRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AttributeName,
			&i.DataType,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
