// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    title,
    role,
    currency,
    inspection_period,
    item_category_id,
    item_name,
    item_description,
    price,
    shipping_method,
    seller_email,
    seller_phone,
    buyer_email,
    buyer_phone,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, title, role, currency, inspection_period, item_category_id, item_name, item_description, price, shipping_method, seller_email, seller_phone, buyer_email, buyer_phone, status, created_at, updated_at
`

type CreateTransactionParams struct {
	Title            sql.NullString  `json:"title"`
	Role             Role            `json:"role"`
	Currency         string          `json:"currency"`
	InspectionPeriod sql.NullString  `json:"inspection_period"`
	ItemCategoryID   uuid.UUID       `json:"item_category_id"`
	ItemName         string          `json:"item_name"`
	ItemDescription  sql.NullString  `json:"item_description"`
	Price            decimal.Decimal `json:"price"`
	ShippingMethod   sql.NullString  `json:"shipping_method"`
	SellerEmail      string          `json:"seller_email"`
	SellerPhone      sql.NullString  `json:"seller_phone"`
	BuyerEmail       string          `json:"buyer_email"`
	BuyerPhone       sql.NullString  `json:"buyer_phone"`
	Status           sql.NullString  `json:"status"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Title,
		arg.Role,
		arg.Currency,
		arg.InspectionPeriod,
		arg.ItemCategoryID,
		arg.ItemName,
		arg.ItemDescription,
		arg.Price,
		arg.ShippingMethod,
		arg.SellerEmail,
		arg.SellerPhone,
		arg.BuyerEmail,
		arg.BuyerPhone,
		arg.Status,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Role,
		&i.Currency,
		&i.InspectionPeriod,
		&i.ItemCategoryID,
		&i.ItemName,
		&i.ItemDescription,
		&i.Price,
		&i.ShippingMethod,
		&i.SellerEmail,
		&i.SellerPhone,
		&i.BuyerEmail,
		&i.BuyerPhone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionWithCategory = `-- name: GetTransactionWithCategory :one
SELECT
    t.id, t.title, t.role, t.currency, t.inspection_period, t.item_category_id, t.item_name, t.item_description, t.price, t.shipping_method, t.seller_email, t.seller_phone, t.buyer_email, t.buyer_phone, t.status, t.created_at, t.updated_at,
    ic.name AS item_category_name,
    ic.description AS item_category_description
FROM transactions t
JOIN item_categories ic ON ic.id = t.item_category_id
WHERE t.id = $1
LIMIT 1
`

type GetTransactionWithCategoryRow struct {
	ID                      uuid.UUID       `json:"id"`
	Title                   sql.NullString  `json:"title"`
	Role                    Role            `json:"role"`
	Currency                string          `json:"currency"`
	InspectionPeriod        sql.NullString  `json:"inspection_period"`
	ItemCategoryID          uuid.UUID       `json:"item_category_id"`
	ItemName                string          `json:"item_name"`
	ItemDescription         sql.NullString  `json:"item_description"`
	Price                   decimal.Decimal `json:"price"`
	ShippingMethod          sql.NullString  `json:"shipping_method"`
	SellerEmail             string          `json:"seller_email"`
	SellerPhone             sql.NullString  `json:"seller_phone"`
	BuyerEmail              string          `json:"buyer_email"`
	BuyerPhone              sql.NullString  `json:"buyer_phone"`
	Status                  sql.NullString  `json:"status"`
	CreatedAt               sql.NullTime    `json:"created_at"`
	UpdatedAt               sql.NullTime    `json:"updated_at"`
	ItemCategoryName        string          `json:"item_category_name"`
	ItemCategoryDescription sql.NullString  `json:"item_category_description"`
}

func (q *Queries) GetTransactionWithCategory(ctx context.Context, id uuid.UUID) (GetTransactionWithCategoryRow, error) {
	row := q.db.QueryRow(ctx, getTransactionWithCategory, id)
	var i GetTransactionWithCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Role,
		&i.Currency,
		&i.InspectionPeriod,
		&i.ItemCategoryID,
		&i.ItemName,
		&i.ItemDescription,
		&i.Price,
		&i.ShippingMethod,
		&i.SellerEmail,
		&i.SellerPhone,
		&i.BuyerEmail,
		&i.BuyerPhone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ItemCategoryName,
		&i.ItemCategoryDescription,
	)
	return i, err
}

const listTransactionsByCategory = `-- name: ListTransactionsByCategory :many
SELECT
    t.id, t.title, t.role, t.currency, t.inspection_period, t.item_category_id, t.item_name, t.item_description, t.price, t.shipping_method, t.seller_email, t.seller_phone, t.buyer_email, t.buyer_phone, t.status, t.created_at, t.updated_at,
    ic.name AS item_category_name,
    ic.description AS item_category_description
FROM transactions t
JOIN item_categories ic ON ic.id = t.item_category_id
WHERE t.item_category_id = $1
ORDER BY t.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByCategoryParams struct {
	ItemCategoryID uuid.UUID `json:"item_category_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

type ListTransactionsByCategoryRow struct {
	ID                      uuid.UUID       `json:"id"`
	Title                   sql.NullString  `json:"title"`
	Role                    Role            `json:"role"`
	Currency                string          `json:"currency"`
	InspectionPeriod        sql.NullString  `json:"inspection_period"`
	ItemCategoryID          uuid.UUID       `json:"item_category_id"`
	ItemName                string          `json:"item_name"`
	ItemDescription         sql.NullString  `json:"item_description"`
	Price                   decimal.Decimal `json:"price"`
	ShippingMethod          sql.NullString  `json:"shipping_method"`
	SellerEmail             string          `json:"seller_email"`
	SellerPhone             sql.NullString  `json:"seller_phone"`
	BuyerEmail              string          `json:"buyer_email"`
	BuyerPhone              sql.NullString  `json:"buyer_phone"`
	Status                  sql.NullString  `json:"status"`
	CreatedAt               sql.NullTime    `json:"created_at"`
	UpdatedAt               sql.NullTime    `json:"updated_at"`
	ItemCategoryName        string          `json:"item_category_name"`
	ItemCategoryDescription sql.NullString  `json:"item_category_description"`
}

func (q *Queries) ListTransactionsByCategory(ctx context.Context, arg ListTransactionsByCategoryParams) ([]ListTransactionsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByCategory, arg.ItemCategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsByCategoryRow{}
	for rows.Next() {
		var i ListTransactionsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Role,
			&i.Currency,
			&i.InspectionPeriod,
			&i.ItemCategoryID,
			&i.ItemName,
			&i.ItemDescription,
			&i.Price,
			&i.ShippingMethod,
			&i.SellerEmail,
			&i.SellerPhone,
			&i.BuyerEmail,
			&i.BuyerPhone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ItemCategoryName,
			&i.ItemCategoryDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :one
UPDATE transactions
SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, role, currency, inspection_period, item_category_id, item_name, item_description, price, shipping_method, seller_email, seller_phone, buyer_email, buyer_phone, status, created_at, updated_at
`

type UpdateTransactionStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status sql.NullString `json:"status"`
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionStatus, arg.ID, arg.Status)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Role,
		&i.Currency,
		&i.InspectionPeriod,
		&i.ItemCategoryID,
		&i.ItemName,
		&i.ItemDescription,
		&i.Price,
		&i.ShippingMethod,
		&i.SellerEmail,
		&i.SellerPhone,
		&i.BuyerEmail,
		&i.BuyerPhone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransaction, id)
	return err
}

